user:
  name: 赛亚人-王常刘

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://187.168.1.1:3306/2004a?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource 

eureka:
  client:
    service-url:
      defaultZone: http://187.168.1.1:8761/eureka


mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.jk.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true